import JSZip from "jszip"
import { saveAs } from "file-saver"
import { Project } from "@/lib/db"

export async function exportToZip(project: Project) {
    const zip = new JSZip()

    // Add package.json
    zip.file("package.json", JSON.stringify({
        name: project.name.toLowerCase().replace(/\s+/g, "-"),
        version: "0.1.0",
        private: true,
        scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "next lint"
        },
        dependencies: {
            "react": "^18",
            "react-dom": "^18",
            "next": "14.2.15",
            "tailwindcss": "^3.4.1",
            "lucide-react": "^0.378.0"
        }
    }, null, 2))

    // Add README
    zip.file("README.md", `# ${project.name}\n\nGenerated by SuperDesign Freedom.\n\n## Setup\n\n1. Run \`npm install\`\n2. Run \`npm run dev\``)

    // Add component code (mock for now, would come from project.nodes)
    const components = zip.folder("components")
    if (components) {
        components.file("App.tsx", `export default function App() { return <div>Hello World</div> }`)
    }

    // Generate blob
    const content = await zip.generateAsync({ type: "blob" })
    saveAs(content, `${project.name}.zip`)
}
